//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int TaskId { get; set; }
        public string Note { get; set; }
        public string Info { get; set; }
        public int State { get; set; }
        public int Type { get; set; }
        public int RoomRoomId { get; set; }
    
        public virtual Rooms Rooms { get; set; }
    }
}
