//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationId { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public bool CheckedIn { get; set; }
        public bool CheckedOut { get; set; }
        public int RoomRoomId { get; set; }
        public string UserUsername { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
